# Site settings
title: hi
name: wheelmaker86  # your name
email: wheelmaker86@gmail.com # your email address
description: >
      wish to be wheelmaker
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wheelmaker86.github.io" # the base hostname & protocol for your site
# twitter_username: itisbenjamin1 # your Twitter username
github_username: wheelmaker86 # your Github username
disqus_username: wheelmaker86 # your disqus username

# google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
